### PR TITLE
Entity relationship diagram

### PR DESCRIPTION
**Pull request by elpotatoslayer**
I created an Entity Relationship Diagram(ERD) for the project.

### CODE REVIEW

**Comment by mimipeshy** [comment]
### STATUS: CHANGES REQUESTED 🔴 ♻️ 

Hello team @Ralph-1   👋🏾 👋🏾 great job on this ERD

#### Highlights :white_check_mark: :white_check_mark:

- [ ]  Well-drawn ERD, it's easy to follow

However, before marking the project as complete please fix the following

- [ ] In an ERD diagram, the relationship between comment and user should be as follows

- One User can create many Comments.
- One Comment is created by only One User.
Enforce a one to many relationship between these tables

That's all :smile: kindly submit another review when done.

_Feel free to reach out to me on slack if you have any questions or something is unclear, or just comment on this PR and tag my name  (@mimipeshy) and I will be glad to help_
Regards
Peris Ndanu

Regards
Peris Ndanu

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Ralph-1  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your this milestone it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ]  In an ERD diagram, the relationship between comment and user should be as follows

> One User can create many Comments.

> One Comment is created by only One User.
### Enforce a one to many relationship between these tables
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @Ralph-1  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your ERD is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have implemented all of the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's because this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
I am sorry to mention this at this time, but this a very mandatory issue to be fixed before you merge on the base branch:
- [ ] It's true that the relationship between user and Friendships is `many-to-many` relationship, but about drawing the story on ERD, it shouldn't be like that way you did it, I have prepared you a small explanation about that and how you should do it, kindly read that explanation below:

Because a friend of a given user is coming from the same table users, then that relationship will be considered as a many-to-many relationship between table users and itself, in that case you will need what we call a junction table between table user and itself to help you implement a many-to-many relationship, that's why you need table frienship => this will be considered as that junction table. I highly recommend you to read [this article](https://support.airtable.com/hc/en-us/articles/218734758-Airtable-s-guide-to-many-to-many-relationships#manytomany) to learn more about the many to many relationship with junction table.
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Review by lekegitrepo — APPROVED** [review]
## Status: Approved :heavy_check_mark:
### Hi @Ralph-1 and @mimipeshy :clap: :clap:
#### Good job :+1: The required changes are implemented.
#### This project is approved :white_check_mark:

#### _Reviewed by Temitayo Adeleke_

**Pull request merged**
